### ISSUE TITLE
dephell convert error: 'NoneType' object has no attribute 'version' 

### ISSUE THREAD

**Issue by CircleOnCircles** [dephell/dephell#151]
## General
**OS**: Pop OS 19.04 ~ ubuntu 19.04
**Install via**:
1. pipenv -> sudo apt install pipenv
2. pipx -> sudo apt install pipx

### Error message
```
$ dephell deps convert
ERROR AttributeError: 'NoneType' object has no attribute 'version' 
```

### pyproject.toml
```toml
[tool.dephell.main]
from = {format = "pipfile", path = "Pipfile"}
to = {format = "pip", path = "requirements.txt"}
```
