### ISSUE TITLE
pipelines

### ISSUE THREAD

**Issue by orsinium** [dephell/dephell#188]
Add pipelines support. Think it's kind of simple ad-hoc makefile for dephell.

For example, convert `pyproject.toml` to `Pipfile` and `requirements.txt` in one command:

```toml
[tool.dephell.pipenv]
from = "pyproject.toml"
to = "Pipfile"

[tool.dephell.pipelines]
convert = [
  {env = "pipenv", command = "deps convert"},
  {env = "pipenv", command = "deps convert", to = "requirements.txt"},
]
```

```bash
$ dephell pipeline convert
```
