### ISSUE TITLE
Local path support for poetry

### ISSUE THREAD

**Issue by MrMrRobat** [dephell/dephell#227]
So, I have this in my `Pipfile`
```toml
[packages]
myshinymodule = {path = "/path/to/myshinymodule-1.0.0.tar.gz"}

```
Then I execute `dephell deps convert --from=Pilfile --to=pyproject.toml`
### Expected result in  `pyproject.toml`:
```toml
[tool.poetry.dependencies]
myshinymodule = {path = "/path/to/myshinymodule-1.0.0.tar.gz"}
```
### Actual result:
```toml
[tool.poetry.dependencies]
myshinymodule = "*"
```
##### `dephell inspect self`:
```json
{
  "cache": "3.00Mb",
  "path": "/home/rocky/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell",
  "python": "/home/rocky/.local/share/dephell/venvs/dephell/bin/python3",
  "version": "0.7.5",
  "versions": {}
}
```
