### ISSUE TITLE
Converted requirements using piplock broken

### ISSUE THREAD

**Issue by Edke** [dephell/dephell#279]
Hello guys.

`dephell` looks really great tool and solves a lot of things for me. 

One thing I found while playing with it and getting it into project's flow was that converting deps from poetry to piplock looks broken.

My pyproject.toml:

```toml
[tool.poetry]
name = "flake8"
version = "0.1.0"
authors = ["Eduard Kracmar <eduard@adaptiware.com>"]

[tool.poetry.dependencies]
python = "==2.*,>=2.7.0"
flake8-import-order = "==0.18.1"
pep8-naming = "==0.8.2"
flake8 = "==3.7.8"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "piplock", path = "requirements.txt"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
Locking to piplock is great, all tools at the end use `pip` so why bother and generate Poetry or Pipenv lock files, requirements.txt with pined versions and hashes work for deterministic builds.

But when I use `dephell deps convert`, my `requirements.txt` file looks like this:
```
enum34==1.1.6; python_version <= "2.7" \
  --hash sha256:2d81cbbe0e73112bdfe6ef8576f2238f2ba27dd0d55752a776c41d38b7da2850 \
  --hash sha256:644837f692e5f550741432dd3f223bbb9852018674981b1664e5dc339387588a \
  --hash sha256:6bd0f6ad48ec2aa117d3d141940d484deccda84d4fcd884f5c3d93c23ecd8c79 \
  --hash sha256:8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1 \
  # ^ from flake8-import-order
flake8-polyfill==1.0.2 \
  --hash sha256:12be6a34ee3ab795b19ca73505e7b55826d5f6ad7230d31b18e106400169b9e9 \
  --hash sha256:e44b087597f6da52ec6393a709e7108b2905317d0c0b744cdca6208e670d8eda \
  # ^ from pep8-naming
pycodestyle==2.5.0 \
  --hash sha256:95a2219d12372f05704562a14ec30bc76b05a5b297b21a5dfe3f6fac3491ae56 \
  --hash sha256:e40a936c9a450ad81df37f549d676d127b1b66000a6c500caa2b085bc0ca976c \
  # ^ from flake8-import-order
setuptools==41.4.0 \
  --hash sha256:7eae782ccf36b790c21bde7d86a4f303a441cd77036b25c559a602cf5186ce4d \
  --hash sha256:8d01f7ee4191d9fdcd9cc5796f75199deccb25b154eba82d44d6a042cf873670 \
  # ^ from flake8-import-order
flake8-import-order==0.18.1 \
  --hash sha256:90a80e46886259b9c396b578d75c749801a41ee969a235e163cfe1be7afd2543 \
  --hash sha256:a28dc39545ea4606c1ac3c24e9d05c849c6e5444a50fb7e9cdd430fc94de6e92 \
  # ^ from flake8
pep8-naming==0.8.2 \
  --hash sha256:01cb1dab2f3ce9045133d08449f1b6b93531dceacb9ef04f67087c11c723cea9 \
  --hash sha256:0ec891e59eea766efd3059c3d81f1da304d858220678bdc351aab73c533f2fbb \
  # ^ from flake8
```

If I compare to `pip-compile` with `requirements.in`:
```
flake8==3.7.8
flake8-import-order==0.18.1
pep8-naming==0.8.2
```
I'm getting on `py27` envionment:
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#

configparser==4.0.2       # via entrypoints, flake8
entrypoints==0.3          # via flake8
enum34==1.1.6             # via flake8, flake8-import-order
flake8-import-order==0.18.1
flake8-polyfill==1.0.2    # via pep8-naming
flake8==3.7.8
functools32==3.2.3.post2  # via flake8
mccabe==0.6.1             # via flake8
pep8-naming==0.8.2
pycodestyle==2.5.0        # via flake8, flake8-import-order                                                                                                                             ────────────────────────────────
pyflakes==2.1.1           # via flake8
typing==3.7.4.1           # via flake8

# The following packages are considered to be unsafe in a requirements file:
# setuptools==41.4.0        # via flake8-import-order
```
and on `PY3` environment:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#

entrypoints==0.3          # via flake8
flake8-import-order==0.18.1
flake8-polyfill==1.0.2    # via pep8-naming
flake8==3.7.8
mccabe==0.6.1             # via flake8
pep8-naming==0.8.2
pycodestyle==2.5.0        # via flake8, flake8-import-order
pyflakes==2.1.1           # via flake8

# The following packages are considered to be unsafe in a requirements file:
# setuptools==41.4.0        # via flake8-import-order
```

What is broken:

- even primary package `flake8` is missing
- locked package list is not complete compared to `pip-compile` output

So what is the difference, how exactly `dephell` produces `piplock` conversion ?
