### ISSUE TITLE
Add option to convert to multiple formats 

### ISSUE THREAD

**Issue by FredHappyface** [dephell/dephell#424]
## Short description

Thanks for this project. It has made the process of using poetry whilst providing requirements.txt and setup.py that bit easier

Would it be possible to add the option to pass multiple output formats or files to? For example:
```bash
dephell deps convert --from=pyproject.toml --to=setup.py,requirements.txt
```

And support something similar in pyproject.toml. For example
```toml
[tool.dephell.main]
from = "pyproject.toml"
to = "setup.py,requirements.txtt"
```

Why?

Currently, in my projects I have to run the following to achieve this
```bash
dephell deps convert
dephell deps convert --from=pyproject.toml --to=setup.py
```

And this change would make for a small quality of life improvement

Thank you for your time
