### ISSUE TITLE
Configuring dephell --env through pyproject.toml

### ISSUE THREAD

**Issue by Luttik** [dephell/dephell#432]
# Short description

Rather than configuring dephell from the command line I prefer to configure it in the pyproject.toml. While this is supported I found that I could not completely replace `dephell deps convert --env main --from Pipfile -- to requirements.txt` by  `dephell deps convert`.

## The expected behavior
*based on how I interpreted the documentation*
``` toml
[tool.dephell]
envs = 'main'
from = 'Pipfile'
to = 'requirements.txt'
```

I would like  `dephell deps convert` to work like `dephell deps convert --env main --from Pipfile -- to requirements.txt` with this configuration.

however if you try that you obtain `ERROR env `main` not found in config`

## Closest implemented behavior
I am aware that you can use 
``` toml
[tool.coverage.report]
show_missing = true
# fail_under = 80
exclude_lines = ["raise NotImplementedError", "[.]{3}"]

[tool.dephell]
envs = 'main'
from = 'Pipfile'
to = 'requirements.txt'
```
and run `dephell deps convert --env main` but since forgetting `--env main` would not return errors but would create the wrong requirements.txt this is undesired.

## Suggested behavior
Since the behavior described at `The expected behavior` might break backwards compatibility I'd suggest introducing an `only_envs` variable to the dephell configuration such that you can configure dephell in this way:
``` toml
[tool.dephell]
only_envs = ['main']
from = 'Pipfile'
to = 'requirements.txt'
```
