### ISSUE TITLE
setup.py formatting issues

### ISSUE THREAD

**Issue by ludaavics** [dephell/dephell#443]
Dephell for setup.py generation and code formatters (e.g. [black](https://github.com/psf/black)) can't be used concurrently as [pre-commit](https://pre-commit.com/) hooks.

```toml
# pyproject.toml
# .. poetry config ..
[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
```

```yaml
# .pre-commit-config.yaml
repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    name: Blacken Python files
    args:
    - --check
- repo: https://github.com/mverteuil/precommit-dephell
  rev: master
  hooks:
    - id: dephell
```
If i try to commit after a `dephell deps convert`, the code formatter check fails.
If I try to format the generated `setup.py`, the dephell pre-commit hook fails.

As a work around, I have excluded `setup.py` from the formatter's pre-commit check:

```yaml
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    name: Blacken Python files
    args:
    - --check
    exclude: setup.py
```

But it would be nice to have it both ways! Perhaps leave setup.py intact if the AST is unchanged?

Thanks!
# Versions

```json
{
  "cache": "0b",
  "path": "/home/ltiako/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell",
  "python": "/home/ltiako/.local/share/dephell/venvs/dephell/bin/python3",
  "version": "0.8.3",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.2",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```
